version: 0.2

phases:
  build:
    commands:
      - dotnet restore dotnet-core-tutorial.csproj
      - dotnet build dotnet-core-tutorial.csproj
      - dotnet publish dotnet-core-tutorial.csproj -o site
  post_build:
    commands:
      - cp aws-windows-deployment-manifest.json ./codebuild/output/src203783356/src/site/
artifacts:
  files:
    - '**/*'
  base-directory: 'codebuild/output/src203783356/src/site/'
  discard-paths: no
