version: 0.2

phases:
  build:
    commands:
      - dotnet restore dotnet-core-tutorial.csproj
      - dotnet build dotnet-core-tutorial.csproj
      - dotnet publish dotnet-core-tutorial.csproj -o site
  post_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - cp aws-windows-deployment-manifest.json $CODEBUILD_SRC_DIR/site/
artifacts:
  files:
    - '**/*'
  base-directory: '$CODEBUILD_SRC_DIR/site/'
  discard-paths: no
