version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -o pipeline
artifacts:
  files:
    - '**/*'
  base-directory: ./bin/Release/netcoreapp3.1/pipeline/publish/
  discard-paths: no
